### PR TITLE
Change path of typo.js

### LINKED ISSUE #4: NBExtension installs but will not validate
I ran `$ jupyter nbextension install https://github.com/Calysto/notebook-extensions/archive/master.zip` and was able to install the extension in /usr/local/share/jupyter/nbextensions. 

However, when I attempt to enable the extension, I get:

```
$ jupyter nbextension enable calico-document-tools
Unrecognized JSON config file version, assuming version 1
Enabling notebook extension calico-document-tools...
      - Validating: problems found:
        - require?  X calico-document-tools
```

Any idea what this error message means?

### PR DESCRIPTION
**Pull request by rschroll**
This fixed #4 for me.

### CODE REVIEW

**Comment by jcb91** [comment]
you can use relative paths in require calls, which is handy if the calysto nbextensions are installed into a non-default location. In that case, you'd use the path `./typo/typo`

**Comment by dsblank** [comment]
@jcb91 That sounds correct. Thanks!

**Comment by rschroll** [comment]
Sorry -- I lost track of this over the holidays.  The relative path seems to work for me.

**Comment by dsblank** [comment]
Thanks!

**Pull request merged**
